# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - restore_cache:
          keys:
            - ruby-kubernetes-controller-{{ checksum "ruby-kubernetes-controller.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - ruby-kubernetes-controller-
      - run:
          name: Install Bundles
          command: bundle check || bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: ruby-kubernetes-controller-{{ checksum "ruby-kubernetes-controller.gemspec" }}
      - run:
          name: Build gem
          command: gem build ruby-kubernetes-controller.gemspec

  test:
    docker:
      - image: circleci/ruby:2.6.3

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - restore_cache:
          keys:
            - ruby-kubernetes-controller-{{ checksum "ruby-kubernetes-controller.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - ruby-kubernetes-controller-
      - run:
          name: Install Bundles
          command: bundle check || bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: ruby-kubernetes-controller-{{ checksum "ruby-kubernetes-controller.gemspec" }}
      - run:
          name:
          command: bundle exec rake test
          when: always
      - store_test_results:
          path: test/reports

  publish:
    docker:
      - image: circleci/ruby:2.6.3

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems.sh

      - run:
          name: Publish to Rubygems
          command: |
            gem build ruby-kubernetes-controller.gemspec
            gem push ruby-kubernetes-controller-$CIRCLE_TAG.gem

workflows:
  version: 2
  development-build:
      jobs:
        - build:
            filters:
              tags:
                only: /^dev.*/
              branches:
                ignore: /.*/
        - test:
            requires:
              - build
            filters:
              tags:
                only: /^dev.*/
              branches:
                ignore: /.*/
  production-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+(\.\d+)*$/
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^\d+(\.\d+)*$/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
            - test
            - build
          filters:
            tags:
              only: /^\d+(\.\d+)*$/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - build
            - test
            - hold
          filters:
            tags:
              only: /^\d+(\.\d+)*$/
            branches:
              ignore: /.*/