# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - restore_cache:
          keys:
            - rubykubernetescontroller-{{ checksum "rubykubernetescontroller.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - rubykubernetescontroller-
      - run:
          name: Install Bundles
          command: bundle check || bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: rubykubernetescontroller-{{ checksum "rubykubernetescontroller.gemspec" }}
      - run:
          name: Build gem
          command: gem build rubykubernetescontroller.gemspec

  test:
    docker:
      - image: circleci/ruby:2.6.3

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - restore_cache:
          keys:
            - rubykubernetescontroller-{{ checksum "rubykubernetescontroller.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - rubykubernetescontroller-
      - run:
          name: Install Bundles
          command: bundle check || bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: rubykubernetescontroller-{{ checksum "rubykubernetescontroller.gemspec" }}
      - run:
          name:
          command: bundle exec rake test >> reports
          when: always
      - store_test_results:
          path: test/reports

#  publish:
#    docker:
#      - image: circleci/ruby:2.6.3
#
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - run:
#          name: Setup Rubygems
#          command: bash .circleci/setup-rubygems.sh
#
#      - run:
#          name: Publish to Rubygems
#          command: |
#            gem build rubykubernetescontroller.gemspec
#            gem push "rubykubernetescontroller-$(git describe --tags).gem"


workflows:
  version: 2
  deployment:
    jobs:
      - build
      - test
#      - publish:
#          requires:
#            - build
#            - test
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore: /.*/
